Add type annotations to controllers/multizone.py
home-assistant-libs/pychromecast pull request #800
Opened 2024-01-23 18:52 UTC by emontnemery

2024-01-23 22:01 UTC, emontnemery commented on pychromecast/controllers/multizone.py
> +        return self._groups[str(group_uuid)]["chromecast"].media_controller  # type: ignore[no-any-return]
The mypy ignore will be removed in an upcoming PR which adds type annotations to the `Chromecast` class

2024-01-26 12:12 UTC, MartinHjelmare requested changes

2024-01-26 12:12 UTC, MartinHjelmare commented on pychromecast/controllers/multizone.py
> +            # "members": set(),
Commented code.

2024-01-26 13:30 UTC, emontnemery commented on pychromecast/controllers/multizone.py
> +            # "members": set(),
```suggestion
```

2024-01-26 13:31 UTC, emontnemery commented on pychromecast/controllers/multizone.py
> +            # "members": set(),
Sorry about that, removed now

2024-01-26 18:08 UTC, MartinHjelmare approved these changes
Thanks!

2024-01-26 18:08 UTC, merged