Expose 'manufacturer' and 'product_name' properties in 'Chromecast' class.
home-assistant-libs/pychromecast pull request #895
Opened 2024-04-17 17:48 UTC by pjgrochowski

Expose 'manufacturer' and 'product_name' properties in 'Chromecast' class.

**[Justification]:**
Field '**model_name**' evaluates to '**Chromecast**' for all device models.
Field '**product_name**' allows to actually distinguish between Chromecast models:
- Chromecast 3 => 'caprica'
- Chromecast Ultra => 'steak'
- Chromecast Android TV => 'sabrina'

2024-08-29 13:57 UTC, elupus submitted a review, later dismissed
I think this make sense. Would map to new field in HA too.

2024-08-30 20:34 UTC, emontnemery reviewed
I'm not fully sure about the benefit of this, why is it better to expose this in a property, instead of accessing via the public `cast_info`?

2024-08-30 20:34 UTC, emontnemery commented on pychromecast/__init__.py
> +            # get_cast_type is guaranteed to return a CastInfo with a non-None model
The comment is misleading

2024-08-30 20:34 UTC, emontnemery commented on pychromecast/__init__.py
> +            # get_cast_type is guaranteed to return a CastInfo with a non-None model
Same

2024-08-30 21:08 UTC, elupus reviewed
Hmm. Didn't realize cast_info was public already. Seem pointless yes. One can wonder why we expose the others then.

2024-08-30 21:19 UTC, elupus requested changes
Missing addition of the new field here:
https://github.com/home-assistant-libs/pychromecast/pull/895/files#diff-c7c448ef8026704bcb4f958857c133335170bbeda706cea0bfeaa033ad829a7dR265
and 
https://github.com/home-assistant-libs/pychromecast/pull/895/files#diff-c7c448ef8026704bcb4f958857c133335170bbeda706cea0bfeaa033ad829a7dR251
and
dial.py

2024-08-31 08:00 UTC, emontnemery commented
> Hmm. Didn't realize cast_info was public already. Seem pointless yes. One can wonder why we expose the others then.

It's due to some old design choice to forward selected attributes and methods from sub-objects to the `Pychromecast` object.

See for example here:
https://github.com/home-assistant-libs/pychromecast/blob/491789843f2bde6c21fe428c387d4064c425a191/pychromecast/__init__.py#L344-L356

It's currently applied very inconsistently; new functionality has not been forwarded like this for several years.

Notice how `media_controller.play_media` is forwarded, but no other methods of it are.

2024-11-13 18:09 UTC, elupus commented
Since no feedback from developer and this change is incomplete, let's close this for now.

2024-11-13 18:09 UTC, closed without merging